apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: shopping-k8s-deployment
  labels:
    app: shopping
spec:
  selector:
    matchLabels:
      app: shopping
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping-k8s
          image: firozehossain01/shopping:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: shopping-service
spec:
  selector:
    app: shopping
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
      type: NodePort # type of the service.
